name: Selenium Tests with Angular Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome-node:
        image: selenium/node-chrome:latest
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven dependencies
        run: mvn clean install -DskipTests

      - name: Start Backend Application
        run: mvn spring-boot:run &

      - name: Wait for Backend to be Ready
        run: |
          echo "Waiting for Backend to be ready..."
          until curl -sSL "http://localhost:8080/actuator/health" | grep '"status":"UP"'; do
            sleep 5
          done
        timeout-minutes: 2

      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          repository: "coundia/astro_angular_tailwindcss_portfolio"
          path: frontend

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install

#      - name: Build and Start Angular App
#        run: |
#          cd frontend
#          npm run build
#          npx http-server -p 4200 -a 0.0.0.0 dist/frontend &

      - name: Wait for Angular App to be Ready
        run: |
          echo "Waiting for Frontend to be ready..."
          until curl -sSL "https://test.pcoundia.com" | grep -q "<title>"; do
            sleep 5
          done
        timeout-minutes: 2

      - name: Wait for Selenium Hub to be Ready
        run: |
          echo "Waiting for Selenium Hub to be ready..."
          until curl -sSL "http://localhost:4444/status" | grep '"ready":true'; do
            sleep 5
          done
        timeout-minutes: 5

      - name: Run Selenium Tests
        run: mvn test
        env:
          SELENIUM_HUB_URL: "http://localhost:4444/wd/hub"
